import React from "react";
import Footer from "../widget/footer";

export default function TermsAndConditions() {
  return (
    <div >
        <div className="px-20 py-10">

        <h1 className="font-bold" style={{fontSize:56}}>Điều khoản & Điều kiện</h1>
        <p className="pt-5">Lorem ipsum dolor sit amet consectetur. Lorem natoque pellentesque nunc nibh elementum sit cursus id. Urna in proin tellus enim amet. Accumsan pellentesque montes tristique id. Nulla sagittis lectus tortor varius nullam. Nunc non lectus amet aliquet fusce.
Accumsan massa fringilla eu purus sit est. Feugiat tortor maecenas ultrices sem augue vulputate euismod facilisis. Dictumst risus tincidunt purus dignissim luctus pretium gravida ut pellentesque. Justo feugiat nam sed sit molestie at sagittis volutpat mattis. Diam eget semper ut proin. Neque massa odio lorem vitae urna amet. Massa sem sed convallis eget morbi et eget suspendisse. Posuere massa a quis lobortis cursus eget. Vel eu lorem fermentum eget. Lacus viverra nec gravida purus. Tortor ullamcorper sit nunc vehicula nunc quis morbi lobortis viverra.
Cras risus quam massa tincidunt tellus faucibus tempor sed. Morbi elementum bibendum amet porta imperdiet sed. Quam nunc gravida sem id varius facilisis arcu at. Ullamcorper nascetur faucibus elementum mi dolor dui in. Duis enim non ultrices vel ut euismod orci sed. A vel justo vulputate et. Leo pharetra orci ac sem id. Ipsum est adipiscing est bibendum lobortis commodo. Pretium ac sit iaculis pharetra facilisis eu commodo iaculis donec. Scelerisque interdum ut eu est a libero ut at pellentesque. Ultrices eu leo et commodo consectetur quis donec tincidunt. Pharetra sit quisque tortor et pharetra lectus ultrices a vitae.
Integer purus vitae feugiat volutpat donec arcu lectus. Potenti platea lectus mi at venenatis et pretium quis nibh. Ac ullamcorper netus gravida et. Ornare viverra scelerisque morbi orci. Pellentesque maecenas viverra id turpis ac. Et consectetur viverra ullamcorper at sed. Dolor at suspendisse sagittis cursus feugiat. Id tempus condimentum dui fringilla fermentum sapien. Massa auctor quis volutpat diam imperdiet nisi ut pellentesque id. Nibh dictum purus magna viverra mi ultrices malesuada sodales cras. Adipiscing ut ultrices sed congue in arcu vestibulum quis.
Amet quis eu sit blandit facilisi. Lacus consequat duis proin commodo felis augue. Ac ultricies maecenas commodo ipsum massa egestas orci urna. Eget ac pulvinar interdum tortor id at urna. Pharetra consectetur laoreet malesuada tincidunt odio varius. Amet adipiscing faucibus orci est gravida non. Quis arcu eget sit eu hendrerit dui aliquam fermentum. Eget suspendisse et adipiscing at porttitor arcu. Porttitor at magnis facilisis felis fermentum. Suspendisse sagittis molestie velit in ultricies aliquam porttitor leo. Donec integer at nullam diam tempor sagittis sed.
Arcu et ultricies pretium viverra. Semper quisque mauris tincidunt tincidunt. Eu blandit aliquet netus et semper. Odio cras ornare nam tristique. Pellentesque sit eget et nisl. Dui lorem feugiat bibendum at nisl imperdiet. Ultricies urna metus nunc leo est ridiculus pellentesque viverra et. Nisl purus ultrices habitant tincidunt aliquet faucibus adipiscing. Nisi elementum ultrices non eu bibendum pulvinar feugiat sit vel. Fringilla tincidunt egestas egestas dui lectus amet. Pellentesque amet augue blandit sed. Eu ullamcorper enim tellus viverra sed ultrices amet blandit. Lacus lacus quis natoque augue rhoncus. Sed lobortis hac magna cursus. Nullam metus adipiscing sodales faucibus dui turpis.
Dictum sodales pharetra neque erat tortor sed lobortis mattis sit. Commodo ac morbi id laoreet eget sapien mauris. Ac sed aliquet ullamcorper praesent. Arcu egestas bibendum diam aliquam. Mauris ut massa adipiscing felis. Interdum nec imperdiet id quis viverra arcu sed. Et tempor mattis id id gravida nec odio. Tempus mi risus faucibus ac tortor elementum hendrerit netus. Eget lorem a integer nullam nulla faucibus. Felis dui velit viverra facilisi nec quam consectetur a viverra. Duis sed aenean amet tempor eu sed luctus enim arcu.
Velit posuere lectus integer tincidunt mi et egestas neque mattis. Interdum habitasse sapien sem ipsum. Neque aliquam nascetur commodo praesent nisl egestas amet. Nam arcu enim urna risus imperdiet massa curabitur mi. Dolor sit vitae massa scelerisque condimentum odio.
Nam eleifend tristique lorem fames sit eleifend turpis porttitor. Ut nisi volutpat neque proin massa. Nec diam nulla mattis ut vestibulum viverra. Facilisis placerat gravida proin nulla. Viverra duis venenatis elementum nec euismod malesuada. Maecenas faucibus gravida purus etiam. Pulvinar ullamcorper eget posuere eu a suspendisse scelerisque justo. Ornare eu cras feugiat morbi risus condimentum urna.
Orci egestas quis nunc nisl lectus molestie amet. Risus pellentesque amet leo nunc viverra integer fermentum est. Eget nunc viverra vitae quis. Et in massa nibh lobortis. Aliquam magnis sed ac lorem sit elementum in pellentesque aliquam. Malesuada sed eu aliquam cursus malesuada. Tincidunt sit et quis ut. Potenti molestie nullam purus vitae placerat nulla. Semper quis a aliquam metus eu. Vel suspendisse ultrices odio pharetra platea eleifend neque etiam. Habitant pulvinar curabitur nisl sed donec pellentesque. Feugiat augue vel dolor elementum ac tempor leo.
Tincidunt leo maecenas massa placerat. Adipiscing leo egestas vehicula tempus nunc egestas. Nam rhoncus faucibus augue viverra ridiculus iaculis auctor. Elit in egestas hendrerit mauris ultricies. Egestas vitae lorem arcu maecenas mi. Tincidunt cursus sed nisl mattis id nunc egestas aliquet. Morbi lacus amet aliquam ornare sollicitudin. Arcu ultrices arcu morbi nibh morbi nisi morbi etiam. Vitae facilisi turpis sed consectetur euismod leo amet sit vivamus.</p>
        </div>

<Footer />
    </div>
  )
}
